services:
  shipDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ship
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    ports:
      - "2022:5432"
  server:
    depends_on:
      - shipDB
    image: quay.io/wildfly/wildfly
    restart: always
    volumes:
      - ./target/Shipping-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war
    ports:
      - "9092:8080"
volumes:
  postgresVolume: {}

